### ISSUE TITLE
When notification isShown, rest of screen is inactive??

### ISSUE THREAD

**Issue by Tristannos** [koukibadr/Elegant-Notification#66]
i have a problem with this and many other snackbar / Toast packages.

When i call the toast than when it pops up on my screen my screen is inresponsive until the toast is cleared.

i think the toast is opening in a Dialog and therefore the rest of the screen is not working.

Doe anyone have a fix for this?

**Comment by koukibadr** [comment]
Hello @Tristannos I just published a newer version of the package I fixed this bug check it out

**Comment by Jip1912** [comment]
> Hello @Tristannos I just published a newer version of the package I fixed this bug check it out

I'm on the newest version but the rest of the screen is still not interactable when a notification is shown.

**Comment by koukibadr** [comment]
> 

Okay I will check what's the problem and publish a new version @Jip1912

**Comment by Ottavio97** [comment]
I also got this problem. Waiting for your fix, thanks a lot @koukibadr

**Comment by koukibadr** [comment]
@Ottavio97  @Jip1912 
I just published a new version check it out it contains the bug fix 
[https://pub.dev/packages/elegant_notification](https://pub.dev/packages/elegant_notification)

**Comment by Ottavio97** [comment]
@koukibadr on my side, the bug is not resolved. I noticed I don't have anymore the dismissible option, but in my project it's not a big deal, but still the underground screen is blocked/inactive/not responsive to touch.

**Comment by koukibadr** [comment]
@Ottavio97 you can pass the `onDismiss` attribute to enable the dismiss of the toast

**Comment by Ottavio97** [comment]
@koukibadr yeah, I've seen the commit, but as I said, it's not a big deal, 'cause the main problem is the blocked background screen. My users experienced this while writing and doing stuff. Hope you can solve it, 'cause my users love your notification style, and honestly all others notification plugin are really invasive or bad looking. I opted for a temporary native Snackbar, but I'm looking forward to your fix. Thanks :)

**Comment by pasleto** [comment]
I have also this problem, this package is so far best looking notification for flutter, but blocking application background when notification pop up is big issue.

**Comment by TOMSLAUS** [comment]
Updating to the latest version did fix the issue for me but I would like to add that now the notification just disappears. It would be nice if the notification would slide back out of the screen, the same way it appeared.

**Comment by luizjunior05** [comment]
I sent a PR #73 that solves this problem.

**Comment by koukibadr** [comment]
Thanks a lot for your contribution @luizjunior05 I will check the PR and upload a new version to fix this issue
